// Security: JSON Web Token

### Her tester vi et simpelt endpoint
GET http://localhost:7070/api/auth/test/

### Her opretter vi en bruger med en user rolle
POST http://localhost:7070/api/auth/register/
Content-Type: application/json

{
    "username": "user",
    "password": "test123"
}

### Her logger vi ind med brugeren
POST http://localhost:7070/api/auth/login/

{
    "username": "user",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

### Her henter vi en bruger med en user rolle
GET http://localhost:7070/api/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Her henter vi en bruger med en admin rolle
GET http://localhost:7070/api/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Her tilføjer vi en superman rolle til brugeren
POST http://localhost:7070/api/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "superman"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Her tilføjer vi en admin rolle til brugeren
POST http://localhost:7070/api/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}



// Guides API

### Her fylder vi databasen med data
GET http://localhost:7070/api/guides/populate
Content-Type: application/json

### Her henter vi alle guides med evt. trips
GET http://localhost:7070/api/guides
Accept: application/json

### Her henter vi en guide ud fra id på guide og hans evt. trips
GET http://localhost:7070/api/guides/5
Accept: application/json

### Her opretter vi en guide
POST http://localhost:7070/api/guides
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "firstname": "Hans",
  "lastname": "Hansen",
  "email": "hanshansen@gmail.com",
  "phone": 12345678,
  "yearsOfExperience": 5
}

### Her opdaterer vi en guide ud fra id på guide
PUT http://localhost:7070/api/guides/5
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "firstname": "Hans",
  "lastname": "Hansen",
  "email": "hanshansen@gmail.com",
  "phone": "12345678",
  "yearsOfExperience": 6
}

### Her sletter vi en guide ud fra id
DELETE http://localhost:7070/api/guides/3
Authorization: Bearer {{jwt_token}}

// Trips API

### Her henter vi alle trips med evt. guides
GET http://localhost:7070/api/trips

### Her henter vi en trip ud fra id
GET http://localhost:7070/api/trips/13

### Her opretter jeg en trip
POST http://localhost:7070/api/trips/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "starttime": "10:00",
  "endtime": "12:00",
  "longitude": "12.345678",
  "latitude": "56.789012",
  "name": "Trip to the beach",
  "price": 100,
  "categoryType": "FOREST"
}

### Her knytter jeg en guide til en trip
PUT http://localhost:7070/api/trips/13/guides/5
Authorization: Bearer {{jwt_token}}

{
"guideId": 5
"tripId": 13
}


### Her opdaterer vi en trip ud fra id
PUT http://localhost:7070/api/trips/13
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "starttime": "10:00",
  "endtime": "12:00",
  "longitude": "12.345678",
  "latitude": "56.789012",
  "name": "Trip to the beach",
  "price": 300,
  "categoryType": "BEACH"
}

### Her sletter vi en trip ud fra id
DELETE http://localhost:7070/api/trips/13
Authorization: Bearer {{jwt_token}}


### Her henter jeg alle trips med en bestemt categoryType
GET http://localhost:7070/api/trips/category/BEACH

{
  "category": "BEACH"
}

### Her henter jeg alle trips med en bestemt guide
GET http://localhost:7070/api/trips/guide/1

{
  "guideId": 5
}

### Her sletter jeg en trip ud fra id
DELETE http://localhost:7070/api/trips/13
Authorization: Bearer {{jwt_token}}

// Packing List Items API

### Her henter vi packingList Items for en trip med categoryType SEA
GET http://localhost:7070/api/trips/packing-list/SEA




